### ISSUE TITLE
No implementation found for void com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport()

### ISSUE THREAD

**Issue by Mitaxing** [LiteAVSDK/Player_Android#108]
【Android】-【7.4.9211】：【No implementation found for void com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport()】
【集成包】：LiteAVSDK_Player_Android_7.4.9211
【当前现象】：Android Studio集成新版本SDK，播放器一个HLS地址的视频，播放直接崩溃，报错如下：No implementation found for void com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport()
【机型】：华为荣耀9
【之前版本有无此问题】：7.4.9211之前没有，7.4.9211有
【有无日志或者截图】：java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport() (tried Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport and Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport__)
        at com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport(Native Method)
        at com.tencent.liteav.basic.datareport.TXCDRApi.<clinit>(TXCDRApi.java:393)
        at com.tencent.liteav.basic.datareport.TXCDRApi.initCrashReport(TXCDRApi.java:372)
        at com.tencent.rtmp.TXVodPlayer.startPlay(TXVodPlayer.java:183)
        at com.tencent.liteav.demo.play.SuperPlayerView.playVodURL(SuperPlayerView.java:402)
        at com.tencent.liteav.demo.play.SuperPlayerView.playWithModel(SuperPlayerView.java:320)
        at com.xing.mita.hao.activity.common.BaseVideoDetailActivity.play(BaseVideoDetailActivity.java:419)
        at com.xing.mita.hao.activity.common.BaseVideoDetailActivity$2.handleMessage(BaseVideoDetailActivity.java:347)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5305)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by 284419487** [comment]
先clean一下项目，然后把APP卸载了重新装

**Comment by lybrooks** [comment]
i have the same  issues

**Comment by yudongdong12306** [comment]
我也是同样问题，偶发崩溃，频率有点高，腾讯一直没有解决，实在不行就用exoplayer了

**Comment by dokieyang** [comment]
请升级到最新版本。
