### ISSUE TITLE
【Android】-【latest.release】：使用最新SDK会报错ClassNotFoundException 必现

### ISSUE THREAD

**Issue by hao321** [LiteAVSDK/Player_Android#109]
【当前现象】：Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.rtmp.sharp.jni.AudioSessionDuplicate" on path: DexPathList[[zip file "/data/app/com.example.livevideodemo-yViVwvXu-DlZCYpeKAAs0Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.livevideodemo-yViVwvXu-DlZCYpeKAAs0Q==/lib/arm64, /data/app/com.example.livevideodemo-yViVwvXu-DlZCYpeKAAs0Q==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tencent.liteav.audio.impl.TXCAudioEngineJNI.nativeNewAudioSessionDuplicate(Native Method)
        at com.tencent.liteav.audio.TXCAudioEngine.CreateInstance(TXCAudioEngine.java:76)
        at com.tencent.liteav.c.<init>(TXCLivePlayer.java:153)
        at com.tencent.liteav.k.a(TXSDKUtil.java:20)

【集成包】：com.tencent.liteav:LiteAVSDK_Player:latest.release
【机型】：不限
【之前版本有无此问题】：今天上午正常，下午开始报错

**Comment by BadReese** [comment]
java.lang.ClassNotFoundException: com.tencent.liteav.basic.util.TXHttpRequest

我的是这个，是因为混淆？我没开混淆呀奇怪

**Comment by yyfeng2003** [comment]
java.lang.ClassNotFoundException: com.tencent.liteav.basic.util.TXHttpRequest

我的也是这个，没开混淆，debug版本是OK的，release版本启动时出现这个错误，无法运行。

**Comment by solovip** [comment]
> java.lang.ClassNotFoundException: com.tencent.liteav.basic.util.TXHttpRequest
> 
> 我的是这个，是因为混淆？我没开混淆呀奇怪

您好，这个您最后解决了么？我也遇到这个问题

**Comment by LeiHolmes** [comment]
HostEngine-PluginManger: create pluginInstance exception: java.lang.ClassNotFoundException: com.tencent.liteav.monet.MonetPlugin
有遇到的大佬吗？更新9.5之后。

**Comment by dokieyang** [comment]
请升级到最新版本。
