### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport() (tried Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport and Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport__)

### ISSUE THREAD

**Issue by BigBrother2018** [LiteAVSDK/Player_Android#129]
【Android】-【8.29808】：【进入播放直接奔溃】
【集成包】：LiteAVSDK_Player_Android_8.29808
【当前现象】：Android Studio集成新版本SDK，播放视频直接奔溃
【机型】：如小米6X 小米NOTE PRO等机型都会
【之前版本有无此问题】：之前使用的是8.1.9717 没有出现该问题 现在使用8.2.9808出现该问题 回退到8.1.9717 依旧有该问题
【有无日志或者截图】：2020-12-24 10:22:33.379 25084-25084/? A/linker: CANNOT LINK EXECUTABLE "/system/bin/dpmd": "/system/lib64/libdpmframework.so" is 32-bit instead of 64-bit
2020-12-24 10:22:35.543 24964-24964/com.app.fengwu E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
    java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport() (tried Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport and Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport__)
        at com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport(Native Method)
        at com.tencent.liteav.basic.datareport.TXCDRApi.<clinit>(TXCDRApi.java:407)
        at com.tencent.liteav.basic.datareport.TXCDRApi.initCrashReport(TXCDRApi.java:386)
        at com.tencent.rtmp.TXVodPlayer.startPlay(TXVodPlayer.java:192)
        at com.tencent.liteav.demo.superplayer.model.SuperPlayerImpl.playVodURL(SuperPlayerImpl.java:423)
        at com.tencent.liteav.demo.superplayer.model.SuperPlayerImpl.playWithModel(SuperPlayerImpl.java:346)
        at com.tencent.liteav.demo.superplayer.model.SuperPlayerImpl.play(SuperPlayerImpl.java:600)
        at com.tencent.liteav.demo.superplayer.SuperPlayerView.playWithModel(SuperPlayerView.java:199)

**Comment by Vander-liu** [comment]
我也遇到这个问题

**Comment by Vander-liu** [comment]
java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport() (tried Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport and Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport__)
        at com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport(Native Method)
        at com.tencent.liteav.basic.datareport.TXCDRApi.<clinit>(TXCDRApi.java:405)
        at com.tencent.liteav.basic.datareport.TXCDRApi.initCrashReport(TXCDRApi.java:384)
        at com.tencent.rtmp.a.a(TXLivePlayerImpl.java:187)
        at com.tencent.rtmp.TXLivePlayer.startPlay(TXLivePlayer.java:114)

**Comment by yforyoung** [comment]
目前最新版LiteAVSDK_Player_8.9.10355    依旧存在这个问题

**Comment by PualGeorge** [comment]
请问使用官方demo能复现此问题吗

**Comment by dokieyang** [comment]
请升级到最新版本。
