### ISSUE TITLE
空指针异常，TXLivePlayer.pause 

### ISSUE THREAD

**Issue by YJYX** [LiteAVSDK/Player_Android#130]
targetSdkVersion : 30，运行在11.0的模拟器上 

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
        at com.tencent.liteav.e.c(TXCDataReport.java:517)
        at com.tencent.liteav.e.c(TXCDataReport.java:259)
        at com.tencent.liteav.h.s(TXCLivePlayer.java:687)
        at com.tencent.liteav.h.a(TXCLivePlayer.java:337)
        at com.tencent.liteav.h.a(TXCLivePlayer.java:363)
        at com.tencent.rtmp.a.b(TXLivePlayerImpl.java:294)
        at com.tencent.rtmp.TXLivePlayer.pause(TXLivePlayer.java:147)

**Comment by Tencent-Alice** [comment]
您好，根据您的描述，可以在真机上进行测试
如有技术问题，欢迎交流 Q2562367495 注明来意

**Comment by kangwf** [comment]
遇到同样的问题，请问有解决方案吗？谢谢~
