### ISSUE TITLE
与exoplayer的冲突

### ISSUE THREAD

**Issue by zx-Zhu** [LiteAVSDK/Player_Android#157]
与exoplayer会有冲突导致crash，堆栈如下

```
06-17 14:59:08.311491 16946 16946 I PlayerManager: [, , 0]:play -> url = https://id.stream.music.joox.com/C400Z011915660d13d.m4a?vkey=D277EFC002B1B901853EF6BD420682365BC9421C1EAA39E880F781EF2638EB0DBDAC62F28F9780DAD729B2E9FC2C36230616D6063BCED5C3&amp;hdnts=exp=1623918548~acl=/*~hmac=b0fc1755ed86d21c90fb368eb0506e1db82cd3283ef2aeae687d82932fa74539&fromtag=8&guid=JOOX@WEB_OPENUDID
06-17 14:59:08.354520 16946 16946 D AndroidRuntime: Shutting down VM
--------- beginning of crash
06-17 14:59:08.355107 16946 16946 E AndroidRuntime: FATAL EXCEPTION: main
06-17 14:59:08.355107 16946 16946 E AndroidRuntime: Process: com.yonyou.cip.sgmw, PID: 16946
06-17 14:59:08.355107 16946 16946 E AndroidRuntime: java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/android/exoplayer2/upstream/BandwidthMeter;)V in class Lcom/google/android/exoplayer2/trackselection/AdaptiveTrackSelection$Factory; or its super classes (declaration of 'com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection$Factory' appears in /data/app/com.yonyou.cip.sgmw-qf8FEI_A-WlHKlrn1860Gg==/base.apk!classes3.dex)
06-17 14:59:08.355107 16946 16946 E AndroidRuntime:  at com.joox.sdklibrary.c.a.<init>(Unknown Source:22)
06-17 14:59:08.355107 16946 16946 E AndroidRuntime:  at com.joox.sdklibrary.player2.d.a(Unknown Source:12)
06-17 14:59:08.355107 16946 16946 E AndroidRuntime:  at com.joox.sdklibrary.player2.d.d(Unknown Source:27)
06-17 14:59:08.355107 16946 16946 E AndroidRuntime:  at com.joox.sdklibrary.player2.d.a(Unknown Source:0)
06-17 14:59:08.355107 16946 16946 E AndroidRuntime:  at com.joox.sdklibrary.player2.d$1.a(Unknown Source:51)
06-17 14:59:08.355107 16946 16946 E AndroidRuntime:  at com.joox.sdklibrary.player2.e.onSuccess(Unknown Source:120)
06-17 14:59:08.355107 16946 16946 E AndroidRuntime:  at com.joox.sdklibrary.kernel.network.SceneBase$1.run(Unknown Source:8)
06-17 14:59:08.355107 16946 16946 E AndroidRuntime:  at android.os.Handler.handleCallback(Handler.java:883)
06-17 14:59:08.355107 16946 16946 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:100)
06-17 14:59:08.355107 16946 16946 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:227)
06-17 14:59:08.355107 16946 16946 E AndroidRuntime:  at android.app.ActivityThread.main(ActivityThread.java:7802)
06-17 14:59:08.355107 16946 16946 E AndroidRuntime:  at java.lang.reflect.Method.invoke(Native Method)
06-17 14:59:08.355107 16946 16946 E AndroidRuntime:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-17 14:59:08.355107 16946 16946 E AndroidRuntime:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
```

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，请提供下build截图，方便进一步定位问题
技术问题 欢迎交流 q2562367495  注明来意
