### ISSUE TITLE
com.tencent.liteav.h$1.a(TXCVodPlayer.java:598)  DiskReadViolation

### ISSUE THREAD

**Issue by forevermgg** [LiteAVSDK/Player_Android#178]
implementation 'com.tencent.liteav:LiteAVSDK_Player:8.9.10355'
android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at libcore.io.BlockGuardOs.read(BlockGuardOs.java:302)
        at libcore.io.ForwardingOs.read(ForwardingOs.java:177)
        at libcore.io.IoBridge.read(IoBridge.java:513)
        at java.io.RandomAccessFile.readBytes(RandomAccessFile.java:387)
        at java.io.RandomAccessFile.read(RandomAccessFile.java:416)
        at java.io.RandomAccessFile.read(RandomAccessFile.java:374)
        at java.io.RandomAccessFile.readLine(RandomAccessFile.java:1003)
        at com.tencent.liteav.basic.util.b.a(CpuUsageMeasurer.java:104)
        at com.tencent.liteav.basic.util.b.b(CpuUsageMeasurer.java:58)
        at com.tencent.liteav.basic.util.b.a(CpuUsageMeasurer.java:51)
        at com.tencent.liteav.basic.util.h.a(TXCSystemUtil.java:62)
        at com.tencent.liteav.h$1.a(TXCVodPlayer.java:598)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，可以具体描述下，方便进一步排查
技术问题 欢迎交流 q2562367495 注明来意

**Comment by dokieyang** [comment]
请升级到最新版本
