### ISSUE TITLE
seek 报错卡顿无法播放

### ISSUE THREAD

**Issue by williamsim** [LiteAVSDK/Player_Android#179]
2021-11-13 17:46:32.353 29928-30024/com.lanyan.live W/Bundle: Key url expected String but value was a java.lang.Integer.  The default value <null> was returned.
2021-11-13 17:46:32.354 29928-30024/com.lanyan.live W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
        at android.os.BaseBundle.getString(BaseBundle.java:1138)
        at com.tencent.liteav.txcvodplayer.TXCVodVideoView$5.onNativeInvoke(TXCVodVideoView.java:781)
        at com.tencent.ijk.media.player.IjkMediaPlayer.onNativeInvoke(IjkMediaPlayer.java:1218)

**Comment by chenqi5256969** [comment]
我也遇到了同样的问题，请问您解决了吗？可以告诉我怎么解决吗

**Comment by chenqi5256969** [comment]
@williamsim 我也遇到了同样的问题，请问您解决了吗？可以告诉我怎么解决吗

**Comment by dokieyang** [comment]
最新版本播放器已经升级了播放内核， 不存在上述问题了， 你可以试试。
