### ISSUE TITLE
java.lang.SecurityException: getDataNetworkTypeForSubscriber

### ISSUE THREAD

**Issue by wanglyGithub** [LiteAVSDK/Player_Android#188]
android操作系统  11
操作机型：OPPO、Vivo 
超级播放器SDK 版本  
![image](https://user-images.githubusercontent.com/17842233/148870977-3a55e5ee-998e-4b43-9d3f-148cd41304b8.png)

出现以下崩溃：
```
01-05 22:08:49.749 26030 26030 E TXCDRApi: TXCDRApi: get network type fail, exception occurred.
01-05 22:08:49.749 26030 26030 E TXCDRApi: java.lang.SecurityException: getDataNetworkTypeForSubscriber
01-05 22:08:49.749 26030 26030 E TXCDRApi: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
01-05 22:08:49.749 26030 26030 E TXCDRApi: 	at android.os.Parcel.createException(Parcel.java:2373)
01-05 22:08:49.749 26030 26030 E TXCDRApi: 	at android.os.Parcel.readException(Parcel.java:2356)
01-05 22:08:49.749 26030 26030 E TXCDRApi: 	at android.os.Parcel.readException(Parcel.java:2298)
01-05 22:08:49.749 26030 26030 E TXCDRApi: 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
01-05 22:08:49.749 26030 26030 E TXCDRApi: 	at java.lang.reflect.Method.invoke(Native Method)
01-05 22:08:49.749 26030 26030 E TXCDRApi: 	at com.jg.bh.b.a.a.invoke(Native Method)
01-05 22:08:49.749 26030 26030 E TXCDRApi: 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
01-05 22:08:49.749 26030 26030 E TXCDRApi: 	at $Proxy3.getNetworkTypeForSubscriber(Unknown Source)
01-05 22:08:49.749 26030 26030 E TXCDRApi: 	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
01-05 22:08:49.749 26030 26030 E TXCDRApi: 	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
01-05 22:08:49.749 26030 26030 E TXCDRApi: 	at com.tencent.liteav.basic.datareport.TXCDRApi.getNetworkType(TXCDRApi.java:323)
01-05 22:08:49.749 26030 26030 E TXCDRApi: 	at com.tencent.liteav.basic.datareport.TXCDRApi.setCommonInfo(TXCDRApi.java:117)
01-05 22:08:49.749 26030 26030 E TXCDRApi: 	at com.tencent.liteav.basic.datareport.TXCDRA
```

**Comment by malikwang** [comment]
同样的问题

**Comment by dokieyang** [comment]
8.2 是比较老的一个版本了，建议升级到10.7 版本
