### ISSUE TITLE
【Harmony】-【8.8.10254】：【播放rtmp录屏崩溃】

### ISSUE THREAD

**Issue by haohe0627** [LiteAVSDK/Player_Android#209]
【Android】-【8.8.10254】：【播放rtmp录屏崩溃】
【集成包】：LiteAVSDK_Player_Android_8.8.10254
【当前现象】：播放rtmp，调用录屏执行startRecord() 方法崩溃
 ndk {//
            abiFilters 'armeabi','armeabi-v7a','arm64-v8a'// 'armeabi', 'arm64-v8a', 'x86', 'x86_64', 'mips', 'mips64'
        }
已经配置相关芯片架构型号。
引用方式：api files('libs\\LiteAVSDK_Player_8.8.10254.aar')
【机型】：华为荣耀10 HRY-AL00a
【之前版本有无此问题】：最新版仍有，三星小米无问题
【有无日志或者截图】：
2022-04-19 19:36:10.759 31354-32206/com.honda.vspAppAndroid E/DEBUG: others_OS: harmony
2022-04-19 19:36:10.759 31354-32206/com.honda.vspAppAndroid E/DEBUG: --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
2022-04-19 19:36:10.759 31354-32206/com.honda.vspAppAndroid E/DEBUG: Process Name: 'com.honda.vspAppAndroid'
2022-04-19 19:36:10.759 31354-32206/com.honda.vspAppAndroid E/DEBUG: Thread Name: 'HWVideoEncoder'
2022-04-19 19:36:10.759 31354-32206/com.honda.vspAppAndroid E/DEBUG: Back traces starts.
2022-04-19 19:36:10.760 31354-32206/com.honda.vspAppAndroid E/DEBUG: java.lang.UnsatisfiedLinkError: No implementation found for long com.tencent.liteav.muxer.jni.TXSWMuxerJNI.init() (tried Java_com_tencent_liteav_muxer_jni_TXSWMuxerJNI_init and Java_com_tencent_liteav_muxer_jni_TXSWMuxerJNI_init__)
2022-04-19 19:36:10.760 31354-32206/com.honda.vspAppAndroid E/DEBUG:     at com.tencent.liteav.muxer.jni.TXSWMuxerJNI.init(Native Method)
2022-04-19 19:36:10.760 31354-32206/com.honda.vspAppAndroid E/DEBUG:     at com.tencent.liteav.muxer.jni.TXSWMuxerJNI.<init>(TXSWMuxerJNI.java:27)
2022-04-19 19:36:10.760 31354-32206/com.honda.vspAppAndroid E/DEBUG:     at com.tencent.liteav.muxer.d.a(TXCMP4SWMuxer.java:132)
2022-04-19 19:36:10.760 31354-32206/com.honda.vspAppAndroid E/DEBUG:     at com.tencent.liteav.muxer.c.a(TXCMP4Muxer.java:103)
2022-04-19 19:36:10.760 31354-32206/com.honda.vspAppAndroid E/DEBUG:     at com.tencent.liteav.a.a.a(TXCStreamRecord.java:304)
2022-04-19 19:36:10.761 31354-32206/com.honda.vspAppAndroid E/DEBUG:     at com.tencent.liteav.videoencoder.b.callDelegate(TXIVideoEncoder.java:178)
2022-04-19 19:36:10.761 31354-32206/com.honda.vspAppAndroid E/DEBUG:     at com.tencent.liteav.videoencoder.a.a(TXCHWVideoEncoder.java:655)
2022-04-19 19:36:10.761 31354-32206/com.honda.vspAppAndroid E/DEBUG:     at com.tencent.liteav.videoencoder.a.b(TXCHWVideoEncoder.java:981)
2022-04-19 19:36:10.761 31354-32206/com.honda.vspAppAndroid E/DEBUG:     at com.tencent.liteav.videoencoder.a.d(TXCHWVideoEncoder.java:40)
2022-04-19 19:36:10.761 31354-32206/com.honda.vspAppAndroid E/DEBUG:     at com.tencent.liteav.videoencoder.a$11.run(TXCHWVideoEncoder.java:1368)
2022-04-19 19:36:10.761 31354-32206/com.honda.vspAppAndroid E/DEBUG:     at android.os.Handler.handleCallback(Handler.java:900)
2022-04-19 19:36:10.761 31354-32206/com.honda.vspAppAndroid E/DEBUG:     at android.os.Handler.dispatchMessage(Handler.java:103)
2022-04-19 19:36:10.762 31354-32206/com.honda.vspAppAndroid E/DEBUG:     at android.os.Looper.loop(Looper.java:219)
2022-04-19 19:36:10.762 31354-32206/com.honda.vspAppAndroid E/DEBUG:     at android.os.HandlerThread.run(HandlerThread.java:67)
2022-04-19 19:36:10.762 31354-32206/com.honda.vspAppAndroid E/DEBUG: Back traces ends.
2022-04-19 19:36:10.762 31354-32206/com.honda.vspAppAndroid E/DEBUG: --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
2022-04-19 19:36:10.762 31354-32206/com.honda.vspAppAndroid E/DEBUG: meminfo:
2022-04-19 19:36:10.762 31354-32206/com.honda.vspAppAndroid E/DEBUG: MemTotal:        3777064 kB

**Comment by DoveBarnett** [comment]
> 【Android】-【8.8.10254】：【播放rtmp录屏崩溃】 【集成包】：LiteAVSDK_Player_Android_8.8.10254 【当前现象】：播放rtmp，调用录屏执行startRecord() 方法崩溃 ndk {// abiFilters 'armeabi','armeabi-v7a','arm64-v8a'// 'armeabi', 'arm64-v8a', 'x86', 'x86_64', 'mips', 'mips64' } 已经配置相关芯片架构型号。 引用方式：api files('libs\LiteAVSDK_Player_8.8.10254.aar') 【机型】：华为荣耀10 HRY-AL00a 【之前版本有无此问题】：最新版仍有，三星小米无问题 【有无日志或者截图】： 2022-04-19 19:36:10.759 31354-32206/com.honda.vspAppAndroid E/DEBUG: others_OS: harmony 2022-04-19 19:36:10.759 31354-32206/com.honda.vspAppAndroid E/DEBUG: --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- 2022-04-19 19:36:10.759 31354-32206/com.honda.vspAppAndroid E/DEBUG: Process Name: 'com.honda.vspAppAndroid' 2022-04-19 19:36:10.759 31354-32206/com.honda.vspAppAndroid E/DEBUG: Thread Name: 'HWVideoEncoder' 2022-04-19 19:36:10.759 31354-32206/com.honda.vspAppAndroid E/DEBUG: Back traces starts. 2022-04-19 19:36:10.760 31354-32206/com.honda.vspAppAndroid E/DEBUG: java.lang.UnsatisfiedLinkError: No implementation found for long com.tencent.liteav.muxer.jni.TXSWMuxerJNI.init() (tried Java_com_tencent_liteav_muxer_jni_TXSWMuxerJNI_init and Java_com_tencent_liteav_muxer_jni_TXSWMuxerJNI_init__) 2022-04-19 19:36:10.760 31354-32206/com.honda.vspAppAndroid E/DEBUG: at com.tencent.liteav.muxer.jni.TXSWMuxerJNI.init(Native Method) 2022-04-19 19:36:10.760 31354-32206/com.honda.vspAppAndroid E/DEBUG: at com.tencent.liteav.muxer.jni.TXSWMuxerJNI.(TXSWMuxerJNI.java:27) 2022-04-19 19:36:10.760 31354-32206/com.honda.vspAppAndroid E/DEBUG: at com.tencent.liteav.muxer.d.a(TXCMP4SWMuxer.java:132) 2022-04-19 19:36:10.760 31354-32206/com.honda.vspAppAndroid E/DEBUG: at com.tencent.liteav.muxer.c.a(TXCMP4Muxer.java:103) 2022-04-19 19:36:10.760 31354-32206/com.honda.vspAppAndroid E/DEBUG: at com.tencent.liteav.a.a.a(TXCStreamRecord.java:304) 2022-04-19 19:36:10.761 31354-32206/com.honda.vspAppAndroid E/DEBUG: at com.tencent.liteav.videoencoder.b.callDelegate(TXIVideoEncoder.java:178) 2022-04-19 19:36:10.761 31354-32206/com.honda.vspAppAndroid E/DEBUG: at com.tencent.liteav.videoencoder.a.a(TXCHWVideoEncoder.java:655) 2022-04-19 19:36:10.761 31354-32206/com.honda.vspAppAndroid E/DEBUG: at com.tencent.liteav.videoencoder.a.b(TXCHWVideoEncoder.java:981) 2022-04-19 19:36:10.761 31354-32206/com.honda.vspAppAndroid E/DEBUG: at com.tencent.liteav.videoencoder.a.d(TXCHWVideoEncoder.java:40) 2022-04-19 19:36:10.761 31354-32206/com.honda.vspAppAndroid E/DEBUG: at com.tencent.liteav.videoencoder.a$11.run(TXCHWVideoEncoder.java:1368) 2022-04-19 19:36:10.761 31354-32206/com.honda.vspAppAndroid E/DEBUG: at android.os.Handler.handleCallback(Handler.java:900) 2022-04-19 19:36:10.761 31354-32206/com.honda.vspAppAndroid E/DEBUG: at android.os.Handler.dispatchMessage(Handler.java:103) 2022-04-19 19:36:10.762 31354-32206/com.honda.vspAppAndroid E/DEBUG: at android.os.Looper.loop(Looper.java:219) 2022-04-19 19:36:10.762 31354-32206/com.honda.vspAppAndroid E/DEBUG: at android.os.HandlerThread.run(HandlerThread.java:67) 2022-04-19 19:36:10.762 31354-32206/com.honda.vspAppAndroid E/DEBUG: Back traces ends. 2022-04-19 19:36:10.762 31354-32206/com.honda.vspAppAndroid E/DEBUG: --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- 2022-04-19 19:36:10.762 31354-32206/com.honda.vspAppAndroid E/DEBUG: meminfo: 2022-04-19 19:36:10.762 31354-32206/com.honda.vspAppAndroid E/DEBUG: MemTotal: 3777064 kB

请问这个8.8.10254版本号是看哪里知道的？

**Comment by haohe0627** [comment]
> 

project 模式，external libraries
