### ISSUE TITLE
腾讯播放器无法播放三个流的视频链接

### ISSUE THREAD

**Issue by Onperson** [LiteAVSDK/Player_Android#213]
2022-05-18 10:40:19.444 18288-18455/com.tencent.liteav.demo E/ent.liteav.dem: No implementation found for int[] com.tencent.thumbplayer.core.common.TPDrm.native_getDRMCapabilities() (tried Java_com_tencent_thumbplayer_core_common_TPDrm_native_1getDRMCapabilities and Java_com_tencent_thumbplayer_core_common_TPDrm_native_1getDRMCapabilities__)
2022-05-18 10:40:19.444 18288-18455/com.tencent.liteav.demo E/PlayerCore: java.lang.UnsatisfiedLinkError: No implementation found for int[] com.tencent.thumbplayer.core.common.TPDrm.native_getDRMCapabilities() (tried Java_com_tencent_thumbplayer_core_common_TPDrm_native_1getDRMCapabilities and Java_com_tencent_thumbplayer_core_common_TPDrm_native_1getDRMCapabilities__)
2022-05-18 10:40:19.446 18288-18455/com.tencent.liteav.demo E/TPDrmCapability: com.tencent.thumbplayer.core.common.TPNativeLibraryException: Failed to call native func.
        at com.tencent.thumbplayer.core.common.TPDrm.getDRMCapabilities(Unknown Source:29)
        at com.tencent.thumbplayer.core.common.TPThumbplayerCapabilityHelper.getDRMCapabilities(Unknown Source:0)
        at com.tencent.thumbplayer.adapter.a.b.a$1.run(Unknown Source:3)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
2022-05-18 10:40:19.484 18288-18288/com.tencent.liteav.demo E/ent.liteav.dem: No implementation found for int com.tencent.thumbplayer.core.downloadproxy.jni.TPDownloadProxyNative.updateStoragePath(int, java.lang.String) (tried Java_com_tencent_thumbplayer_core_downloadproxy_jni_TPDownloadProxyNative_updateStoragePath and Java_com_tencent_thumbplayer_core_downloadproxy_jni_TPDownloadProxyNative_updateStoragePath__ILjava_lang_String_2)
2022-05-18 10:40:19.484 18288-18288/com.tencent.liteav.demo E/[tpdlnative][TPDownloadProxy:0]: updateStoragePath failed, error:java.lang.UnsatisfiedLinkError: No implementation found for int com.tencent.thumbplayer.core.downloadproxy.jni.TPDownloadProxyNative.updateStoragePath(int, java.lang.String) (tried Java_com_tencent_thumbplayer_core_downloadproxy_jni_TPDownloadProxyNative_updateStoragePath and Java_com_tencent_thumbplayer_core_downloadproxy_jni_TPDownloadProxyNative_updateStoragePath__ILjava_lang_String_2)
2022-05-18 10:40:19.490 18288-18288/com.tencent.liteav.demo E/HostEngine-PluginManger: create pluginInstance exception, pluginId|2|clazzName|com.tencent.liteav.monet.MonetPlugin is not install in dex!!
2022-05-18 10:40:19.490 18288-18288/com.tencent.liteav.demo E/HostEngine-RenderProcessService: connectPlayer，postProcessService can not work!!

**Comment by dokieyang** [comment]
不是这个原因导致无法播放的， 方便提供更多log吗
