### ISSUE TITLE
【android】-【11.1.0.13141@aar】：运行报错

### ISSUE THREAD

**Issue by 1420965446** [LiteAVSDK/Player_Android#224]
【当前现象】：运行报错
【集成包】：通过com.tencent.liteav:LiteAVSDK_Player:latest.release集成的 LiteAVSDK_Player:11.1.0.13141@aar
【机型】：iqoo 3
【之前版本有无此问题】：不确定
【有无日志或者描述、截图】：
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1142)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:701)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:553)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:500)
                                                                                                    	at com.tencent.liteav.demo.superplayer.SuperPlayerView.initView(SuperPlayerView.java:154)
                                                                                                    	at com.tencent.liteav.demo.superplayer.SuperPlayerView.initialize(SuperPlayerView.java:146)
                                                                                                    	at com.tencent.liteav.demo.superplayer.SuperPlayerView.<init>(SuperPlayerView.java:131)
                                                                                                    	at com.zszs.activity.video.player.feed.player.FeedPlayerView.initViews(FeedPlayerView.java:80)
                                                                                                    	at com.zszs.activity.video.player.feed.player.FeedPlayerView.<init>(FeedPlayerView.java:43)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:876)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1064)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1019)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1181)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1142)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:701)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:553)
                                                                                                    	at com.zszs.activity.video.player.feed.feedlistview.FeedListItemView.initViews(FeedListItemView.java:58)
                                                                                                    	at com.zszs.activity.video.player.feed.feedlistview.FeedListItemView.<init>(FeedListItemView.java:46)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:876)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1064)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1019)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:678)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:553)
                                                                                                    	at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.runInner(AsyncLayoutInflater.java:188)
                                                                                                    	at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.run(AsyncLayoutInflater.java:202)
                                                                                                    Caused by: java.lang.RuntimeException: Can't create handler inside thread Thread[Thread-27,5,main] that has not called Looper.prepare()
                                                                                                    	at android.os.Handler.<init>(Handler.java:227)
                                                                                                    	at android.os.Handler.<init>(Handler.java:129)
                                                                                                    	at android.view.GestureDetector$GestureHandler.<init>(GestureDetector.java:308)
                                                                                                    	at android.view.GestureDetector.<init>(GestureDetector.java:423)
                                                                                                    	at android.view.GestureDetector.<init>(GestureDetector.java:400)
                                                                                                    	at com.tencent.liteav.demo.superplayer.ui.player.WindowPlayer.initialize(WindowPlayer.java:108)
                                                                                                    	at com.tencent.liteav.demo.superplayer.ui.player.WindowPlayer.<init>(WindowPlayer.java:95)

**Comment by dokieyang** [comment]
从我们开源的代码来看， 是在main thread 创建view的， 你这边是否进行其它改动
